# Generated by Django 6.0.6 on 2026-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchresults',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
